#!/bin/bash
# This file is intended to be used on Windows systems with Cygwin installed
# and the MSVC tools in that path. I use vim to edit, so it's nice to never
# have to pull up the GUI.

MODE='Release|Win32'

case $1 in
	ex*)
		vcbuild examples/osgcairodrawspeed/osgcairodrawspeed.vcproj "${MODE}"
		strace ./examples/osgcairodrawspeed/Release/osgcairodrawspeed.exe
	;;

	in*)
		vcbuild INSTALL.vcproj "${MODE}"
	;;

	un*)
		vcbuild UNINSTALL.vcproj "${MODE}"
	;;

	re*)
		vcbuild /rebuild osgCairo.sln "${MODE}"
	;;

	*)
		vcbuild osgCairo.sln "${MODE}"
		./${0} in
	;;
esac

